### ISSUE TITLE
[JOSS] Segfault during example run

### ISSUE THREAD

**Issue by PaulDebus** [itsoulos/GlobalOptimus#5]
I compiled the program using `qmake GlobalOptimus.pro` and `make`. When running any optimization, for instance the example from the JOSS paper, the program segfaults.

Here is the output from one such run:

```
❯ ./GlobalOptimus --opt_problem=rastrigin --opt_method=Genetic --opt_iters=1 --opt_seed=10 --opt_debug=yes
Executions:    1
===================
RUN:    1 BEST VALUE:                   -2 FUNCTION CALLS: 14177
Average Function calls:             14177.00
Minimum Function Value:                   -2
Percent Minimum  Found:               100.00%
Standard Deviation of Function Calls:                    0
Segmentation fault (core dumped)
```

(also, the output does not match the example in the paper, but this is for later)

**Comment by itsoulos** [comment]
It does not crash in Debian Linux with Qt version 5.15.8. 

Maybe I should check it in a fedora laptop.

**Comment by itsoulos** [comment]
I have pushed i small fix in the software that fixed that error

**Comment by PaulDebus** [comment]
Yes, that seems to have been it. 

It still does not reproduce the output shown in the paper, but numerically I can reproduce the results
